name: Tests

on: [ push ]

env:
  DEFAULT_RUBY: 2.7.7

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'
      -
        name: Install ruby ${{ env.DEFAULT_RUBY }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.DEFAULT_RUBY }}
      -
        name: Run Lint
        run: |
          gem install rubocop
          gem install rubocop-performance
          gem install rubocop-gitlab-security
          gem install rubocop-rake
          gem install rubocop-rspec
          rubocop --parallel

  ci:

    needs: lint

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            name: "Default"
            ruby: 2.7.7
            rails: 'latest'
            gemfile: Gemfile
          -
            ruby: 2.7.7
            rails: 7.0
            gemfile: gemfiles/rails_5_2.gemfile
          -
            ruby: 2.7.7
            rails: 6.1
            gemfile: gemfiles/rails_6_1.gemfile
          -
            ruby: 3.0.5
            rails: 6.1
            gemfile: gemfiles/rails_6_1.gemfile
          -
            ruby: 3.1.3
            rails: 7.0
            gemfile: gemfiles/rails_7_0.gemfile
          -
            ruby: head
            rails: 7.0
            gemfile: gemfiles/rails_7_0.gemfile
          -
            ruby: head
            rails: 'head'
            gemfile: gemfiles/rails_edge.gemfile

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      BUNDLE_WITHOUT: production
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3

    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'
      -
        name: Install ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      -
        name: Set Bundle ${{ matrix.gemfile }}
        run: |
          gem update --system
          gem install bundler
      -
        name: Bundle Install ${{ matrix.gemfile }}
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install
      -
        name: Run test suite ${{ matrix.ruby }} x ${{ matrix.rails }}
        run: |
          echo $BUNDLE_GEMFILE
          bundle exec rake test